### ISSUE TITLE
ACF image array

### ISSUE THREAD

**Issue by jaydickinson** [OriginalEXE/Optimize-Images-Resizing#1]
Hi First off great plugin.

Is there anyway to get this to work with the ACF image array feature/image object? The below will regenerate all custom Image sizes and not just the one specified.

<code>$image['sizes']['custom_size'];</code>

http://www.advancedcustomfields.com/resources/image/

this might be a advanced custom field issue?
Thanks

**Comment by OriginalEXE** [comment]
Hello, I replied to you on wordpress.org forum, pasting my response here:

Hello,

I took a look into the plugin. I don't think I will be able to help you out here, if you want to avoid generating all image sizes with Advanced Custom Fields plugin, you will have to use Image ID as a return value and then grab the rest of the data you need (alt tags etc) manually.

What Advanced Custom Fields does (when you use array as a return format) is that it checks for each registered image size and stores it's value into array (as it does not know which image size you will actually use). This checking is recognized as a request so image size is normally generated.

So technically, there is nothing that can be done by me, the only way I see this changing is if Advanced Custom Fields developer would add another option for you to choose which image size you need in your array, no other way to solve this.
